// 서버가 body.code로 내려주는 오류 코드
export const API_ERROR_CODE = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  ENTERPRISE_INACTIVE: 'ENTERPRISE_INACTIVE',
  ENTERPRISE_NOT_FOUND: 'ENTERPRISE_NOT_FOUND',
  NO_CHANGED_VALUE: 'noChangedValue',
  NO_UPDATE_FIELD: 'NO_UPDATE_FIELD',
}
